version: 0.2
phases:
  build:
    commands:
      - echo Entered the build space
      - mvn clean package
  post_build:
    commands:
      - echo Build complete success
artifacts:
  files:
    - target/aws-CodePipeLine-0.0.1-SNAPSHOT.jar
  discard-paths: yes
